config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :posts do
    member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
    end
  end

  resources :users
  resources :posts do
      resources :comments, only: [:create, :destroy]
  end

  root 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates_presence_of :content
    validates_length_of :content, minimum: 1

    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	acts_as_votable

	has_paper_trail
	belongs_to :category
	validates_presence_of :title, :content, :category_id
	validates_length_of :title, minimum: 5
	validates_length_of :content, minimum: 8
	validates_presence_of :anonymous, :allow_blank => true

	def score
  		self.get_upvotes.size - self.get_downvotes.size
  	end

  	def self.search(query)
  		if query.present?
  			where(['title LIKE :query OR content LIKE :query', query: "%#{query}%"])
  		else
  			all
  		end
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_voter
    has_many :posts
    has_many :comments

    validates :email, email_format: { message: "O formato do email está errado!" }

    validates_presence_of :email , :full_name 
    validates_uniqueness_of :email

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def require_authentication
        unless logged_in?
            redirect_to root_path, alert: "Necessita estar logado!"
        end
    end

    def require_no_authentication
        if logged_in?
            redirect_to root_path, alert: "Já se encontra logado!"
        end
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_authentication, only: [:create, :destroy]
    before_action :can_destroy, only: [:destroy]
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to post_path(@post.id)
        else
            redirect_to @post, alert: "Houve um erro ao criar o comentário"
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end

    def can_destroy
        unless logged_in? && comment.user == current_user
                redirect_to post_path(params[:post_id])
        end
    end

    def comment
           @comment = Post.find(params[:post_id]).comments.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_authentication, only: [:new, :create, :edit, :update, :destroy, :upvote, :downvote, :show]
	before_action :can_edit, only: [:edit, :update]

	def upvote
		@post = Post.find(params[:id])
    	@post.upvote_by current_user

    	redirect_to :back
    end

    def downvote
		@post = Post.find(params[:id])
    	@post.downvote_by current_user
    	redirect_to :back
    end

	def index
		if params[:category].blank? && params[:q].present?
			@search_query = params[:q]
			posts = Post.search(@search_query)
			@posts = posts.order("cached_votes_score DESC")
		elsif params[:category].present? && params[:q].blank?
			@category_id = Category.find_by(name: params[:category]).id
			posts = Post.where(category_id: @category_id)
			@posts = posts.order("cached_votes_score DESC")
		elsif params[:category].blank? && params[:q].blank?
			@posts = Post.all.order("cached_votes_score DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@search_query = params[:q]
			posts_with_categories = Post.where(category_id: @category_id)
			posts = posts_categories.search(@search_query)
			@posts = posts.order("cached_votes_score DESC")
		end
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to post_path(@post), notice: "Post criado com sucesso!"
		else
			render action: :new
		end
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.order("created_at DESC")
	end

	def edit
			@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to post_path(@post), notice: "Post atualizado com sucesso!"
		else
			render action: :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, notice: "Post deletado com sucesso!"
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :category_id, :anonymous)
	end

	def can_edit
	    unless logged_in? && post.user == current_user
	            redirect_to post_path(params[:id])
	    end
	end

	def post
	       @post ||= Post.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_no_authentication, only: [:new, :create]
    before_action :require_authentication, only: [:destroy]

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to user
        else
            flash.now[:danger] = 'Email ou senha errados'
            render 'new'
        end
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def destroy
        log_out
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_authentication, only: [:show, :edit, :update]
    before_action :require_no_authentication, only: [:new, :create]

    before_action :can_change, only: [:edit, :update]

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
                  log_in user 
                    redirect_to user,
                        notice: 'Cadastrado com sucesso!'
        else
            render action: :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user ,
                notice: 'Cadastro atualizado com sucesso!'
        else
            render action: :edit
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.
            require(:user).
            permit(:email, :full_name, :password, :password_confirmation)
    end

    def can_change
        unless logged_in? && current_user == user
            redirect_to user_path(params[:id])
        end
    end

    def user
        @user ||= User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end 
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end   

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>

<p>
    Feito por: <b><%= link_to comment.user.full_name, comment.user %></b>
</p>

<p>
    <b><%= comment.content %></b>
</p>

<p>
    <%= time_ago_in_words(comment.created_at) %> atrás
</p>

<% if comment.user == current_user %>
    <%= link_to "Deletar", [comment.post, comment], method: :delete, data: {confirm: "Tem certeza disso?"}%>
<% end %>

<hr>

<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>

   <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--6-col" >
		<%= f.label :content, "Comentário", class:"mdl-textfield__label"%> 
		<%= f.text_area :content, class:"mdl-textfield__input big-textarea" %>
   </div>

    <p><%= f.submit "Criar comentário", class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %></p>

<% end %>

app/views/home/index.html.erb
<h1 class="titulo">Bem vindos ao prORT!</h1>
<br>
<h5 class="descricao">
   Aqui é o lugar onde você que está conectado ao ORT terá um espaço para se expressar!<br>
   Seja você um aluno, funcionário ou professor, escreva aqui suas idéias, sejam elas sugestões, reclamações e elogios :)
</h5>
<br>


<div class="col-md-3" id="aluno">
	<div class="info">
		<b><h4>Alan Klajman</h4>
		<i>SM &amp; Desenvolvedor</i>
	</div>
</div>

<div class="col-md-3" id="aluno">
	<div class="info">
		<b><h4>Thor Garcia</h4></b>
		<i>SM &amp; Desenvolvedor</i>
	</div>
</div>

<div class="col-md-3" id="aluno">
	<div class="info">
		<b><h4>Ana Braga</h4></b>
		<i>SM</i>
	</div>
</div>

<div class="col-md-3">
	<div class="info" id="aluno">
		<b><h4>Gustavo Sampaio</h4></b>
		<i>SM</i>
	</div>
</div>
	<div class="info" id="aluno">
		<b><h4>Vitor Araújo</h4></b>
		<i>SM</i>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		 <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  		<title>prORT</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
                          <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
                          <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>

	<body>
    <% if logged_in? %>
      <div class="demo-layout-waterfall mdl-layout mdl-js-layout">
          <header class="mdl-layout__header mdl-layout__header--waterfall">
          <div class="mdl-layout__header-row">
              <span class="mdl-layout-title">prORT</span>
              <div class="mdl-layout-spacer"></div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
              <label class="mdl-button mdl-js-button mdl-button--icon" for="waterfall-exp">
                  <i class="material-icons">search</i> <br>
              </label>

              <div class="mdl-textfield__expandable-holder">
                <%= form_tag posts_path, method: :get do %>
                    <%= text_field_tag :q, @search, class: "mdl-textfield__input", id: "waterfall-exp", placeholder: "Procure algum post!" %>
                  <% end %>
              </div>
        </div>
      </div>
      <div class="mdl-layout__header-row">
          <div class="mdl-layout-spacer"></div>
              <nav class="mdl-navigation">
                  <%= link_to  "Home", root_path, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Novo post", new_post_path, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Todos os posts", posts_path, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Perfil", current_user, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Logout", logout_path, method: "delete",  class: "mdl-navigation__link grande mdl-color-text--white" %>
              </nav>
          </div>
      </header>
      <div class="mdl-layout__drawer">
      <span class="mdl-layout-title" id="waterfallTitle">prORT</span>
      <nav class="mdl-navigation">
        <%= link_to  "Home", root_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "Novo post", new_post_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "todos os posts", posts_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "Perfil", current_user, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "Logout", logout_path, method: "delete",  class: "mdl-navigation__link grande mdl-color-text--black" %>
      </nav>
      </div>

    <% else %>

        <div class="demo-layout-waterfall mdl-layout mdl-js-layout">
          <header class="mdl-layout__header mdl-layout__header--waterfall">
          <div class="mdl-layout__header-row">
              <span class="mdl-layout-title">prORT</span>
              <div class="mdl-layout-spacer"></div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
              <label class="mdl-button mdl-js-button mdl-button--icon" for="waterfall-exp">
                  <i class="material-icons">search</i>
              </label>

              <div class="mdl-textfield__expandable-holder">
                <input class="mdl-textfield__input" type="text" name="sample" id="waterfall-exp">
              </div>
        </div>
      </div>
      <div class="mdl-layout__header-row">
          <div class="mdl-layout-spacer"></div>
              <nav class="mdl-navigation">
                  <%= link_to  "Home", root_path, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Cadastrar", new_user_path, class: "mdl-navigation__link grande mdl-color-text--white" %>
                  <%= link_to  "Login", login_path, class: "mdl-navigation__link grande mdl-color-text--white" %>

              </nav>
          </div>
      </header>
      <div class="mdl-layout__drawer">
      <span class="mdl-layout-title" id="waterfallTitle">prORT</span>
      <nav class="mdl-navigation">
        <%= link_to  "Home", root_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "Cadastrar", new_user_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
        <%= link_to  "Login", login_path, class: "mdl-navigation__link grande mdl-color-text--black" %>
      </nav>
      </div>
    <% end %>
        <main class="mdl-layout__content">
          <div class="page-content">
              <% if notice.present? %>
                <div class="notice">
                  <%= notice %>
                </div>
              <% end %>
              <% if alert.present? %>
                <div class="alert">
                  <%= alert %>
                </div>
              <% end %>
              <%= yield %>
          </div>
        </main>

    <% if current_page?(:controller => 'home', :action => 'index') == false %>
      <footer class="mdl-mini-footer mdl-color--grey-750">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">prORT</div>
            <ul class="mdl-mini-footer__link-list">
              <li><a href="#">Contato</a></li>
              <li><a href="#">Termos de compromisso</a></li>
            </ul>
        </div>
      </footer>
    <% end %>
      </div>
	</body>
</html>

app/views/posts/edit.html.erb
<div class="edit-post">
	<% if @post.errors.any? %>
		<ul>
			<% @post.errors.full_messages.each do |error| %>
				<li class="error-msg"><%= error %></li>
			<% end %>
		</ul>
	<% end %>


	<h3>Atualize o post!</h3>

	<%= form_for @post do |f| %>

		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--6-col" >
			<%= f.label :title, "Título ", class:"mdl-textfield__label" %>
			<%= f.text_field :title, class:"mdl-textfield__input" %>
		</div>

		<br> <br>

		<p>
			<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Escolha uma categoria para o post" } %>
		</p>

		<br> <br>


		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--6-col" >
			<%= f.label :content, "Escreva!", class:"mdl-textfield__label" %> <br>
			<%= f.text_area :content, class:"mdl-textfield__input big-textarea" %>
		</div>

		<br> <br>


		<label class="mdl-cell mdl-cell--6-col mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="anemona" >
			<%= f.check_box :anonymous, id: "anemona", class:"mdl-checkbox__input" %>
			<%= f.label "Anônimo?", {}, {class: "mdl-checkbox__label"} %>
		</label>

		<br> <br>


		<p>
			<%= f.submit "Editar post", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
		</p>

	<% end %>
</div>

app/views/posts/index.html.erb
<div class="categorias">
    <p>
      <% Category.all.each do |category| %>
        <%= link_to category.name, posts_path(category: category.name), class:"mdl-button mdl-js-button" %>
      <% end %>
    </p>
</div>
<% if @posts.count == 0 && params[:category].blank? && params[:q].blank? %>
  <center><h2>Não possuimos nenhum post até o momento!</h2></center>
<% elsif @posts.count == 0 && params[:category].present? && params[:q].blank? %>
  <center><h2>Não possuimos nenhum post com determinada categoria até o momento!</h2></center>
<% elsif @posts.count == 0 && params[:category].blank? && params[:q].present? %>
  <center><h2>Não possuimos nenhum post com determinado termo de pesquisa!</h2></center>
<% else %>
<div class="mdl-grid">
    <% @posts.each do |post| %>
                              <div class="mdl-cell mdl-cel--4-col" >
                                <div class="mdl-card mdl-shadow--2dp" id="post-card-index">
                                    <div class="mdl-card__title">
                                        <h2 class="mdl-card__title-text"><%= link_to post.title, post_path(post) %></h2>
                                    </div>
                                    <div class="mdl-card__supporting-text">
                                        <b><%=  truncate(post.content, length: 25) %></b>
                                    </div>
                                    <div class="mdl-card__actions mdl-card--border">
                                         <% if post.anonymous == '1' %>
                                               <p><b>Autor</b>: Anônimo</p>
                                          <% else %>
                                              <p><b>Autor</b>: <%= post.user.full_name %></p>
                                          <% end %>

                                         <p><b>Pontuação</b>: <%= post.score %> </p>

                                          <% if post.category != nil %>
                                              <p><b>Categoria</b>: <%= post.category.name %></p>
                                          <% end %>

                                          <p><b>Criado há</b>: <%= time_ago_in_words(post.created_at) %></p>
                                    </div>
                                    <div id="avaliacao-index">
                                        <%= link_to "Gostei", like_post_path(post), method: :put,  class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent" %>
                                        <%= link_to "Não gostei", dislike_post_path(post), method: :put,  class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
                                    </div>
                                </div>
                              </div>
                            <br><br>
    <% end %>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="post-new">
	<% if @post.errors.any? %>
		<ul>
			<% @post.errors.full_messages.each do |error| %>
				<li class="error-msg"><%= error %></li>
			<% end %>
		</ul>
	<% end %>


	<h3>Crie um post:</h3>

	<%= form_for @post do |f| %>

		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--6-col" >
			<%= f.label :title, "Título", class:"mdl-textfield__label" %>
			<%= f.text_field :title, class:"mdl-textfield__input" %>
		</div>

		<br> <br>

		<p>
			<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Escolha uma categoria para o post" } %>
		</p>

		<br> 

		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--6-col" >
			<%= f.label :content, "Escreva!", class:"mdl-textfield__label"%> 
			<%= f.text_area :content, class:"mdl-textfield__input big-textarea" %>
		</div>

		<br> <br>


		<label class="mdl-cell mdl-cell--6-col mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="anemona" >
			<%= f.check_box :anonymous, id: "anemona", class:"mdl-checkbox__input" %>
			<%= f.label "Anônimo?", {}, {class: "anemona mdl-checkbox__label"} %>
		</label>

		<br> <br>


		<p>
			<%= f.submit "Criar post", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
		</p>

	<% end %>
</div>

app/views/posts/show.html.erb
<% if @post.user == current_user %>
  <center>
    <br>
  	  <%= link_to "Editar post", edit_post_path(@post.id), class:"mdl-button mdl-js-button" %>
  	  <%= link_to 'Apagar post', post_path, :method => :delete, data: { confirm: "Tem certeza disso?" }, class:"mdl-button mdl-js-button" %>
      <br><br>
  </center>
<% end %>
<br>
<div class="mdl-card mdl-shadow--2dp" id="show-post-card">
  <div class="mdl-card__title">
      <center><h2 class="mdl-card__title-text" id="title_show"><%= link_to @post.title, post_path(@post) %></h2></center>
  </div>
  <div class="mdl-card__supporting-text">
      <h6><b><%= @post.content %></b></h6>
  </div>
  <div class="mdl-card__actions mdl-card--border">
       <% if @post.anonymous == '1' %>
             <p><b>Autor</b>: Anônimo</p>
        <% else %>
            <p><b>Autor</b>: <%= @post.user.full_name %></p>
        <% end %>

       <p><b>Pontuação</b>: <%= @post.score %> </p>

        <% if @post.category != nil %>
            <p><b>Categoria</b>: <%= @post.category.name %></p>
        <% end %>

        <p><b>Criado há</b>: <%= time_ago_in_words(@post.created_at) %></p>
  </div>
  <div>
      <%= link_to "Gostei", like_post_path(@post), method: :put,  class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent" %>
      <%= link_to "Não gostei", dislike_post_path(@post), method: :put,  class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
  </div>
  <div class="mdl-card__actions mdl-card--border" id="comentarios">
  	<% if @post.comments.count == 0 %>
		  <h5>Não temos comentários para esse post até o momento.</h5>
	   <% elsif @post.comments.count == 1 %>
		  <h5>Temos um comentário:</h5>
		  <%= render "comments/comment" %>
	  <% else %>
		  <h5>Temos <%= @post.comments.count %> comentários:</h5>
		  <%= render "comments/comment" %>
	  <% end %>
	  <h6>Adicione um comentário!</h6>
	  <%= render "comments/form" %>
  </div>
  <br>
</div>

app/views/users/edit.html.erb
<center>
<h4>Editar perfil</h4>

<% if @user.errors.any? %>
    <div id= "error_explanation">
        <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li class="error-msg"><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
    
<%= form_for @user do |f| %>
    <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col"id="full_name">
        <%= f.label :full_name, "Nome completo", class:"mdl-textfield__label" %>
        <%= f.text_field :full_name, class:"mdl-textfield__input" %>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="email_new">
        <%= f.label :email, "Email", class:"mdl-textfield__label" %>
        <%= f.text_field :email, class:"mdl-textfield__input" %>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="password_new">
        <%= f.label :password,"Senha", class:"mdl-textfield__label" %>
        <%= f.password_field :password, class:"mdl-textfield__input" %>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="password_confirm">
        <%= f.label :password_confirmation, "Confirme a senha", class:"mdl-textfield__label" %>
        <%= f.password_field :password_confirmation, class:"mdl-textfield__input" %>
    </div>
    <br>
  <%= f.submit "Atualizar", class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
<% end %>
</center>

app/views/users/new.html.erb
<div class="new-user">
    <% if @user.errors.any? %>
        <div id= "error_explanation">
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li class="error-msg"><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

        <h3>Cadastre-se</h3>

    <%= form_for @user do |f| %>
        <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col"id="full_name">
            <%= f.label :full_name, "Nome completo", class:"mdl-textfield__label" %>
            <%= f.text_field :full_name, class:"mdl-textfield__input" %>
        </div>
        <br>
        <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="email_new">
            <%= f.label :email, "Email", class:"mdl-textfield__label" %>
            <%= f.text_field :email, class:"mdl-textfield__input" %>
        </div>
        <br>
        <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="password_new">
            <%= f.label :password,"Senha", class:"mdl-textfield__label" %>
            <%= f.password_field :password, class:"mdl-textfield__input" %>
        </div>
        <br>
        <div class="mdl-textfield mdl-js-textfield mdl-cell--6-col" id="password_confirm">
            <%= f.label :password_confirmation, "Confirme a senha", class:"mdl-textfield__label" %>
            <%= f.password_field :password_confirmation, class:"mdl-textfield__input" %>
        </div>
        <br>
      <%= f.submit "Cadastre-se", class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    <% end %>
    </center>
</div>

app/views/users/show.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Perfil</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <h5>
      Nome: <%= @user.full_name %>
      <br><br>
      Email: <%= @user.email %>
      <br><br><br><br>
    </h5>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <%= link_to 'Editar Perfil', edit_user_path(@user), class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
  </div>
</div>